- name: create ubuntu group
  group:
    name: ubuntu
    state: present

- name: create ubuntu user
  user:
    name: ubuntu
    group: ubuntu

- name: Set /var/www ownership
  file:
    path: /var/www
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
